canaltirant:
  - code: 'editorial'
    url: 'localhost:3005'
  - code: 'libreria'
    url: 'localhost:3005'
  - code: 'libmex'
    url: 'localhost:3005'
  - code: 'tol'
    url: 'localhost:3005'
  - code: 'formacion'
    url: 'localhost:3005'
  - code: 'tase'
    url: 'localhost:3005'
  - code: 'tnr'
    url: 'localhost:3005'
  - code: 'biblioteca'
    url: 'localhost:3005'
  - code: 'corporativa'
    url: 'localhost:3005'
  - code: 'tph'
    url: 'localhost:3005'
  - code: 'tolmex'
    url: 'localhost:3005'
  - code: 'conmex'
    url: 'localhost:3005'
  - code: 'latam'
    url: 'localhost:3005'
  - code: 'analytics'
    url: 'localhost:3005'
  - code: 'teoriayderecho'
    url: 'localhost:3005'
  - code: 'formacionmexico'
    url: 'localhost:3005'
  - code: 'libbra'
    url: 'localhost:3005'
  - code: 'formacionbrasil'
    url: 'localhost:3005'
  - code: 'bvbrasil'
    url: 'localhost:3005'
  - code: 'libchl'
    url: 'localhost:3005'
  - code: 'libcol'
    url: 'localhost:3005'
  - code: 'compliancers'
    url: 'localhost:3005'
